DROP TABLE IF EXISTS stats;
DROP TABLE IF EXISTS posts;

CREATE TABLE stats (
	ord INTEGER PRIMARY KEY NOT NULL,
	title TEXT NOT NULL,
	subtitle TEXT NOT NULL,
	commmand TEXT NOT NULL,
	parser TEXT,
	id TEXT NOT NULL
);

CREATE TABLE posts (
	title TEXT PRIMARY KEY,
	content TEXT NOT NULL,
	quicklinks TEXT NOT NULL
);